solver:  
  gradient_accumulation_steps: 1
  per_device_batch_size: 1
  logging_steps: 100
  resume_from_checkpoint: ''
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: false
  gradient_checkpointing: false 
  max_train_steps: 50000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: false 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'
  # optimizer
  use_8bit_adam: false
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

model:
  add_attention: true
  in_channels: 24
  out_channels: 8
  down_block_types:
    - DownBlock3D
    - DownBlock3D
    - DownBlock3D
    - DownBlock3D
    - AttnDownBlock3D
  up_block_types:
    - AttnUpBlock3D
    - UpBlock3D
    - UpBlock3D
    - UpBlock3D
    - UpBlock3D
  block_out_channels: 
    - 64
    - 128
    - 256
    - 512
    - 1024

val:
  validation_steps: 10000
  validation_steps_tuple: []

dataset:
  dataset_path: data/couple_spout_3D
  depth: 256
  height: 64
  width: 64
  skip_timestep: 1

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false
  prediction_type: "v_prediction"

inference:
  dilation_radius: 3
  num_inference_steps: 100
  

weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.
noise_offset: 0.
snr_gamma: 0.
enable_zero_snr: True 

seed: 42
exp_name: 'exp3_complex_model' 
output_dir: 'exp'
