solver:  
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: false
  gradient_checkpointing: false 
  max_train_steps: 200000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: false 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'
  # optimizer
  use_8bit_adam: false
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 10000
  validation_steps_tuple: []

dataset_path: data/couple_spout_3D

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_bs: 1
logging_steps: 100

weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.
noise_offset: 0.
snr_gamma: 0.
enable_zero_snr: True 

skip_timestep: 1
seed: 12580
resume_from_checkpoint: ''
exp_name: '1'
output_dir: 'exp'

prediction_type: "v_prediction"